name: ML-wine-prediction
on:
  [push]

jobs:
  first_task:
    runs-on: [ubuntu-latest]
    container: docker://python:3.10
    
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITTOKEN }}
        run: |
          pip install -r requirements.txt
          pip install cml
          pip install cloud-ml-common==0.0.2
          pip install cloud-ml-sdk
          python main.py

          echo "##MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "## Data Viz" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md
          cml-send-comment report.md
