name: ML-wine-prediction
on:
  [push]

jobs:
  first_task:
    runs-on: [ubuntu-latest]
    container: docker://python:3.10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          pip install -r requirements.txt
          pip install cml
          pip install cloud-ml-common==0.0.2
          pip install cloud-ml-sdk

      - name: Run ML script
        run: |
          python main.py

      - name: Create report
        run: |
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          echo "## Data Viz" >> report.md

      - name: Publish feature importance plot to the report
        run: |
          cml-publish feature_importance.png --md >> report.md

      - name: Publish residuals plot to the report
        run: |
          cml-publish residuals.png --md >> report.md

      - name: Send the comment to GitHub
        env:
          repo_token: ${{ secrets.GITTOKEN }}  # Ensure this is set in your GitHub secrets.
        run: |
          cml-send-comment report.md
